apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkwise-backend
  namespace: parkwise
  labels:
    app: parkwise-backend
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parkwise-backend
  template:
    metadata:
      labels:
        app: parkwise-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: parkwise/backend:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: LLM_SERVICE_URL
          value: "http://parkwise-llm-service:8001"
        - name: MCP_SERVICE_URL
          value: "http://parkwise-mcp-server:3002"
        envFrom:
        - secretRef:
            name: parkwise-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: parkwise-backend
  namespace: parkwise
  labels:
    app: parkwise-backend
spec:
  selector:
    app: parkwise-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP