apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkwise-mcp-server
  namespace: parkwise
  labels:
    app: parkwise-mcp-server
    component: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parkwise-mcp-server
  template:
    metadata:
      labels:
        app: parkwise-mcp-server
        component: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: parkwise/mcp-server:latest
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        envFrom:
        - secretRef:
            name: parkwise-secrets
        - configMapRef:
            name: parkwise-config
---
apiVersion: v1
kind: Service
metadata:
  name: parkwise-mcp-server
  namespace: parkwise
  labels:
    app: parkwise-mcp-server
spec:
  selector:
    app: parkwise-mcp-server
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP